add modul failed

diff --git a/.github/workflows/cypress.yml b/.github/workflows/cypress.yml
--- a/.github/workflows/cypress.yml
+++ b/.github/workflows/cypress.yml
@@ -17,7 +17,11 @@ jobs:
         run: docker build -t cypress-test .
 
       - name: Run Cypress tests (Docker)
-        run: docker run --rm cypress-test || echo "CYPRESS_FAILED=true" >> $GITHUB_ENV
+        run: |
+            mkdir -p results
+            docker run --rm \
+            -v ${{ github.workspace }}/results:/app/results \
+            cypress-test || echo "CYPRESS_FAILED=true" >> $GITHUB_ENV
 
       - name: Send Telegram Notification
         if: always()
@@ -45,3 +49,20 @@ jobs:
           curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
           -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
           -d text="$MESSAGE"
+
+      - name: Extract failed tests
+        if: always()
+        run: |
+          if [ -f results/results.json ]; then
+            FAILED_TESTS=$(jq -r '
+            .tests[] | select(.state=="failed") |
+            "- " + .title
+            ' results/results.json)
+          else
+            FAILED_TESTS="No results.json found"
+          fi
+
+            echo "FAILED_TESTS<<EOF" >> $GITHUB_ENV
+            echo "$FAILED_TESTS" >> $GITHUB_ENV
+            echo "EOF" >> $GITHUB_ENV
+
